### ISSUE TITLE
Better notification when database or volume has been pushed

### ISSUE THREAD

**Issue by zizther** [weareferal/craft-sync#17]
At the moment when I push a database backup to S3, it currently says it has completed the task, however in the S3 bucket nothing has been pushed, and there are no errors in the CP.

Is it possible to have better validation/messaging when things are sent and not?

I have `Craft 3 queue` enabled.

I did run a test without Craft queue enabled, and it did work.

Craft 3.4.4.1 with Env Sync 1.0.14

**Comment by timmyomahony** [comment]
Yeah, the problem here is that when the queue is enabled, all the feedback means after hitting the button is that the task was successfully added to the queue. If there's an issue when the actual queue job is run then you just get a red 'x' or a tick in the queue item. I wonder is there any way to notify the user with a pop-up when the queue job complete/doesn't complete? 

When not using the queue you should get immediate feedback if there is an error (otherwise it should have pushed to S3) via a notification at the top of the window.

**Comment by zizther** [comment]
That is correct, I did test both ways, with out the queue system I get an alert.

**Comment by timmyomahony** [comment]
Craft has just updated the queue system which might make it easier to get feedback from jobs

**Comment by timmyomahony** [comment]
Closing this as the notifications in `remote-sync` and `remote-back` should be much clearer now
