### ISSUE TITLE
PHP Error on Accessing the Sync Page

### ISSUE THREAD

**Issue by masonry47** [weareferal/craft-sync#24]
Hi there!

We are trying out the plugin and are getting a PHP error on accessing the Sync.  It installs fine and we can enter all of our S3 credentials succesfully but when accessing the actual "Sync" in utilities we get 

 [-][1][8bou240t7e1tfui3ofc9p8duf5][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 1 in ../public_html/vendor/weareferal/env-sync/src/services/SyncService.php:50

Craft version is 3.3.8 along with the most recent version of the plugin. 

Thanks in advance for any ideas!

**Comment by timmyomahony** [comment]
Hi @masonry47 I think this might have to do with having existing backups already in the `storage/backups` folder of your app. Is this the case?

The plugin [uses a slightly different filename format for backups](https://github.com/weareferal/craft-env-sync/blob/master/src/services/SyncService.php#L46) and I think this error is related to it having trouble trying to parse the old backups filenames (the reason for this is to give a bit more context in the dropdown menus so that you can see what backups you have for what environment)

I think I need to handle this better in the code, reverting to the standard filename format that Craft generated by default if there is an error. 

In the meantime, could you temporarily move your backups out of the `storage/backups` folder to somewhere else safe and try again? If this is not an option I understand. I will work on fixing the error either way.

**Comment by masonry47** [comment]
Thanks!

That did it.  For now that is fine because we are testing on some staging
environments.  Thanks again for the quick help.

**Comment by masonry47** [comment]
@timmyomahony 

Just a quick FYI that removing the old DB backups from the folder did work, but once we did the "create local backup" option, we now get the error again, I'm assuming because the folder now has a file in there again, even though the backup was for sure created by the plugin. 

Thanks again!

**Comment by timmyomahony** [comment]
Oh weird. Can you post the filename here and I can test it locally to see what's up?

**Comment by masonry47** [comment]
@timmyomahony Meaning the name of the .sql backup that was created by the plugin?

It looks like this

test-site_staging_200228_142435_dymsvf7zzq_v3.3.8.sql

thanks!

**Comment by timmyomahony** [comment]
Thanks for that. Strangely that works OK for me. I also made a standard Craft backup via the exisiting "database backup" utility tab and that appeared OK in the sync utility tab.

Have in got `v1.1.0` installed (as opposed to `v1.0.X`)?

**Comment by masonry47** [comment]
Just deleted the file, and went through the process again multiple times.  So just to clarify when I removed the native craft backups, I am able to load the sync utility, then I click the "create database backup", it does successfully create the backup, but as soon as it is complete, the page reloads and then shows the PHP error and Stack Trace.  The backup is sitting in the folder by itself, and after I delete it, I can load the sync utility page again..... We do have 1.1 installed.

**Comment by masonry47** [comment]
In playing with different environments, I think we narrowed in on the problem. Some of our environments have a hyphen so the .sql file will have that in the file name and this breaks it.  If the environment name is just a string with no hyphens all is good.  

So all good for now.  thanks for your help!

**Comment by timmyomahony** [comment]
Ah OK. I see. I only anticipated single-word environments (`dev` `staging` and `production`). I appreciate you taking the time to hunt down the problem. I'm going to add a change to the regex to allow for hyphens in the environment - should be an easy fix.

**Comment by timmyomahony** [comment]
Should work with https://github.com/weareferal/craft-env-sync/tree/v1.1.1
